import { Metadata } from "next";
import "../styles/globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className='antialiased bg-gradient-to-tr from-blue-50 to-blue-100'
      >
        {children}
      </body>
      <footer className="mt-auto text-gray-500 text-sm py-6 text-center">
        © 2024 - Data table Next.js
      </footer>
    </html>
  );
}
