import { Metadata } from "next";
import "../styles/globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className='antialiased bg-secondary font-sans'
      >
        {children}
      </body>
      <footer className="mt-auto text-white text-sm pt-8 pb-10 flex justify-around h-14 bg-secondary">
        <div>© 2024 Kub, Tous Droits Réservés.</div>
        <div className="flex justify-evenly w-96">
          <div className="hover:text-primary hover:cursor-pointer">A propos</div>
          <div className="hover:text-primary hover:cursor-pointer">Politique de confidentialité</div>
        </div>
      </footer>
    </html>
  );
}
