import Footer from '@/src/components/layout/Footer';
import { LangProvider } from '@/src/provider/LangProvider';
import '@/src/styles/globals.css';
import '@fontsource/roboto';
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: {
    locale: string
  };
}>) {
  return (
    <LangProvider locale={params.locale}>
      <html lang="en">
        <body
          className='antialiased bg-secondary font-sans'
        >
          {children}
        </body>
        <Footer>
        </Footer>
      </html >
    </LangProvider>
  );
}
